### PR TITLE
Adding support for ICU plurals. Resolves #98.

### LINKED ISSUE #98: Support ICU format for plurals
**Is your feature request related to a problem? Please describe.**

I am using [Transifex](transifex.com) for storing all of my translations, which only supports [ICU Format for pluralization](https://docs.transifex.com/formats/json#section-plurals-support).

I would love if babel-plugin-18next-extract supported an option to generate the ICU format for plurals instead of i18next's default format.

**Describe the solution you'd like**

What this means is that instead of generating this:
```json
{
  "itemCount": "{{count}} item",
  "itemCount_plural": "{{count}} items"
}
```

I want this to be generated:
```json
{
  "itemCount": "{count, plural, one {{count} item} other {count} items}}"
}
```

I suggest that a new boolean option, `icuPlurals`, be added to support this.

**Describe alternatives you've considered**

I've considered just living with the i18next format that has multiple keys instead of the one key with ICU format. This is not ideal because the Transifex translation UI does not know how to handle those keys as a plural string, but it DOES know how to handle the ICU string as plurals. Transifex presents a special UI to translators when the ICU format is correctly presented.

**Additional context**

### PR DESCRIPTION
**Pull request by joeldenning**
See #98. I did not add tests yet because I wanted to get feedback on whether this PR is worth polishing up, if there's a different approach that would be better, or if it should be abandoned in favor of a middleware as proposed in #110 

I did not alter the existing plural functionality, but just put it inside of an else statement. The github diff is a bit deceiving about the size of the change.

### CODE REVIEW

**Comment by gilbsgilbs** [comment]
Thanks @joeldenning . FYI, you can append [`?w=1` to the diff URL](https://github.com/gilbsgilbs/babel-plugin-i18next-extract/pull/112/files?w=1) in order to get a diff that ignores whitespace changes. Way more satisfying isn't it?

image

**Comment by joeldenning** [comment]
👍 that does make the diff look a lot nicer.

**Comment by joeldenning** [comment]
I just updated this with the latest changes to master. It is ready for review.

**Comment by gilbsgilbs** [comment]
Sorry for the delay once again :zipper_mouth_face: .

I think I'm fine with those changes. I suggest that we let it undocumented for now and that we call the option `experimentalIcuSupport` to prevent users from using it extensively because I don't really want to maintain it myself THB. So unless I find other regular contributors, I may drop it as soon as we have middlewares (as long as it can be done through middleware obviously).

Thanks for your contributions btw :) .

**Comment by joeldenning** [comment]
Great, I will plan on adding tests for this then and will mark it as ready for review once I do so.

**Comment by joeldenning** [comment]
@gilbsgilbs I added a test and have marked this as mergeable and ready for review.

**Comment by gilbsgilbs** [comment]
Thanks @joeldenning and happy new year 🎊🥳 . I took the liberty of renaming the option to `enableExperimentalIcu` (since if I understand correctly, support is partial for now) and I have documented it with a notice. I'll release it tonight.

**Comment by joeldenning** [comment]
Awesome, thank you!

**Pull request merged**
